"""Update columns

Revision ID: d213ca7a89cd
Revises: f4a0a895b6b5
Create Date: 2022-02-12 16:03:43.555139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd213ca7a89cd'
down_revision = 'f4a0a895b6b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('title', sa.String(), nullable=False))
    op.add_column('pitches', sa.Column('category', sa.String(), nullable=False))
    op.add_column('pitches', sa.Column('post', sa.String(), nullable=False))
    op.drop_column('pitches', 'Pitches')
    op.drop_column('pitches', 'upvotes')
    op.drop_column('pitches', 'downvotes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('downvotes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('pitches', sa.Column('upvotes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('pitches', sa.Column('Pitches', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('pitches', 'post')
    op.drop_column('pitches', 'category')
    op.drop_column('pitches', 'title')
    # ### end Alembic commands ###
